### ISSUE TITLE
Pre-signed URL

### ISSUE THREAD

**Issue by boboshko** [smashah/picoS3#16]
Hey!

Can I use `pico-s3` to generate a pre-signed URL?

**Comment by smashah** [comment]
Hi

Not yet. If you want you can contribute to resolve #1

Which service do you need the signed URL from?

**Comment by boboshko** [comment]
Thanks for the offer, but I am a product designer, not a developer. It is very difficult for me to understand other people's code.

I need pre-signed URLs for DigitalOcean Spaces.

**Comment by smashah** [comment]
available in 2.6.0
